name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_dotenv: ^5.1.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  go_router: ^13.2.2

flutter:
  uses-material-design: true

  assets:
    - .env


